src/Entity/Task.php
<?php
/**
 * Created by PhpStorm.
 * User: kseniya
 * Date: 29.09.18
 * Time: 9:56
 */

namespace App\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=1024)
     * @var string
     */
    private $text;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @var string
     */
    private $full_text;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $create_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $public_date;

    /**
     * @ORM\Column(type="boolean")
     * @var bool
     */
    private $important_task;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tasks")
     */
    private $author;

    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="tasks")
     */
    private $category;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="tasks")
     */
    private $tags;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="task")
     */
    private $comments;

    /**
     * @var ArrayCollection
     * @ORM\OneToMany(targetEntity="App\Entity\LikeItem", mappedBy="task")
     */
    private $likeItems;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likeItems = new ArrayCollection();
        $this->important_task = false;
        $this->create_date = new \DateTime('now');
    }

    public function __toString()
    {
        return $this->text;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getFullText(): ?string
    {
        return $this->full_text;
    }

    public function setFullText(?string $full_text): self
    {
        $this->full_text = $full_text;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function getPublicDate(): ?\DateTimeInterface
    {
        return $this->public_date;
    }

    public function setPublicDate(?\DateTimeInterface $public_date): self
    {
        $this->public_date = $public_date;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTask($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTask() === $this) {
                $comment->setTask(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LikeItem[]
     */
    public function getLikeItems(): Collection
    {
        return $this->likeItems;
    }

    public function addLikeItem(LikeItem $likeItem): self
    {
        if (!$this->likeItems->contains($likeItem)) {
            $this->likeItems[] = $likeItem;
            $likeItem->setTask($this);
        }

        return $this;
    }

    public function removeLikeItem(LikeItem $likeItem): self
    {
        if ($this->likeItems->contains($likeItem)) {
            $this->likeItems->removeElement($likeItem);
            // set the owning side to null (unless already changed)
            if ($likeItem->getTask() === $this) {
                $likeItem->setTask(null);
            }
        }

        return $this;
    }

    /**
     * @param bool $important_task
     * @return Task
     */
    public function setImportantTask(bool $important_task): Task
    {
        $this->important_task = $important_task;
        return $this;
    }

    /**
     * @return bool
     */
    public function isImportantTask(): bool
    {
        return $this->important_task;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}interactive{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/fontawesome-all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <a class="navbar-brand" href="">
            {% if is_granted("ROLE_USER") %}
                {{ app.user.username }}
            {% endif %}
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ path('homepage') }}">Новости</a>
            </li>
            {% if is_granted("ROLE_USER") %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('profile') }}">Профиль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_registration_register') }}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('fos_user_security_login') }}">Войти</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>
<div class="container pt-4">
    <div class="row">
        <div class="col mx-auto">
            {% set notices = app.flashes('notice') %}
            {% set errors = app.flashes('error') %}

            {% if notices %}
                {% for message in notices %}
                    <div class="notice">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}

            {% if errors %}

                {% for message in errors %}
                    <div class="error">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <div class="row">
            {% block content %}{% endblock %}
    </div>

</div>

{% block javascripts %}
    <script src="{{ asset('vendor/jquery/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('vendor/popper/js/popper.min.js') }}"></script>
    <script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
{% endblock %}
</body>
</html>

templates/categories.html.twig
{% if categories is defined %}
    <h4>Категории</h4>
    <ul>
    {% for category in categories %}
        <li>
            <a href="{{ path('news_category', {'category':category.id}) }}">{{ category.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% endif %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Новости
{% endblock %}



{% block content %}
    <div class="col-3 sidebar">
        {{ render(controller(
            'App\\Controller\\IndexController::ShowCategoriesAction'
        )) }}
        {{ render(controller(
            'App\\Controller\\IndexController::ShowTagsAction', {'category':category}
        )) }}
    </div>
    <div class="col-9">
        {% if message is defined %}
            <p style="color: red">{{ message }}</p>
        {% endif %}
        <h1>Новости</h1>

        {% if news is defined %}
            <div style="background: yellow; padding: 20px;">
                {% for task in news %}
                    {% if task.importantTask %}
                        <br/>
                        <div class="news_item">
                            <div class="info">
                                <p class="category"><b>Категория:</b> {{ task.category.title }}</p>
                                <p class="author"><b>Автор:</b> {{ task.author.username }}</p>
                                <p class="тэги"><b>Тэги:</b> {% for tag in task.tags %}{{ tag.title }}, {% endfor %}</p>
                            </div>
                            <div class="date">
                                <p class="create"><em>Дата создания: {{ task.createDate | date('d.m.Y') }}</em></p>
                                <p class="public"><em>Дата публикации: {{ task.publicDate | date('d.m.Y') }}</em></p>
                            </div>
                            <p>{{ task.text }}</p>
                            <div>
                                <a href="{{ path('news_item', {'id':task.id}) }}">Подробнее...</a>
                            </div>
                        </div>
                        {% if user.id is defined %}
                            {{ render(controller(
                                'App\\Controller\\IndexController::ShowLikeButtons', {'task':task.id}
                            )) }}
                        {% endif %}
                        <br/>
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
            {% for task in news %}
                {% if not task.importantTask %}
                    <br/>
                    <div class="news_item">
                        <div class="info">
                            <p class="category"><b>Категория:</b> {{ task.category.title }}</p>
                            <p class="author"><b>Автор:</b> {{ task.author.username }}</p>
                            <p class="тэги"><b>Тэги:</b> {% for tag in task.tags %}{{ tag.title }}, {% endfor %}</p>
                        </div>
                        <div class="date">
                            <p class="create"><em>Дата создания: {{ task.createDate | date('d.m.Y') }}</em></p>
                            <p class="public"><em>Дата публикации: {{ task.publicDate | date('d.m.Y') }}</em></p>
                        </div>
                        <p>{{ task.text }}</p>
                        <div>
                            <a href="{{ path('news_item', {'id':task.id}) }}">Подробнее...</a>
                        </div>
                    </div>
                    {% if user.id is defined %}
                        {{ render(controller(
                            'App\\Controller\\IndexController::ShowLikeButtons', {'task':task.id}
                        )) }}
                    {% endif %}
                    <br/>
                    <hr>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% if pages is defined %}
            {% for page in pages%}
                {% if category is defined %}
                    <a href="{{ path('news', {'page':page, 'limit':5, 'category':category}) }}">{{ page }}</a>
                {% else %}
                    <a href="{{ path('news', {'page':page, 'limit':5}) }}">{{ page }}</a>
                {% endif %}|
            {% endfor %}
        {% endif %}

        {% if user.id is defined %}
            <br/>
            <br/>
            <br/>
            <h4>Добавить новость</h4>
            <br/>
            <br/>
            {{ form(form) }}
            <br/>
            <br/>
            <br/>
        {% endif %}
        <br/>
        <br/>
    </div>

{% endblock %}

templates/like_buttons.html.twig
{% if  likes is defined%}

<br/>
<br/>
<div class="like_buttons">
    <span class="border p-2">{{ likes.quality }} </span>
    <a href="{% if likes.quality_active %}{{ path('make_like', {'task':task, 'type':'quality', 'val':1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Качественно</a>
    <a href="{% if likes.quality_active %}{{ path('make_like', {'task':task, 'type':'quality', 'val':-1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Некачественно</a>
    <br/>
    <span class="border p-2">{{ likes.actuality }} </span>
    <a href="{% if likes.actuality_active %}{{ path('make_like', {'task':task, 'type':'actuality', 'val':1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Актуально</a>
    <a href="{% if likes.actuality_active %}{{ path('make_like', {'task':task, 'type':'actuality', 'val':-1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Не актуально</a>
    <br/>
    <span class="border p-2">{{ likes.happiness }} </span>
    <a href="{% if likes.happiness_active %}{{ path('make_like', {'task':task, 'type':'happiness', 'val':1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Доволен</a>
    <a href="{% if likes.happiness_active %}{{ path('make_like', {'task':task, 'type':'happiness', 'val':-1}) }}{% else %}#{% endif %}" class="btn btn-dark m-1">Недоволен</a>
    <br/>
</div>
<br/>

{% endif %}

templates/news_task.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Новость
    {% if news_task is defined %}
        {{ news_task.publicDate | date('d.m.Y') }}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="col-3 sidebar">
        {{ render(controller(
            'App\\Controller\\IndexController::ShowCategoriesAction'
        )) }}
    </div>
    <div class="col-9">
        <h3>Новость</h3>
        {% if message is defined %}
            <p style="color: red">{{ message }}</p>
        {% endif %}
        <div class="news_item_content">
            <div class="info">
                <p class="category"><b>Категория:</b> {{ news_task.category.title }}</p>
                <p class="author"><b>Автор:</b> {{ news_task.author.username }}</p>
                <p class="тэги"><b>Тэги:</b> {% for tag in news_task.tags %}{{ tag.title }}, {% endfor %}</p>
            </div>
            <div class="date">
                <p class="create"><em>Дата создания: {{ news_task.createDate | date('d.m.Y') }}</em></p>
                <p class="public"><em>Дата публикации: {{ news_task.publicDate | date('d.m.Y') }}</em></p>
            </div>
            {% if news_task.fullText is defined %}
                {{ news_task.fullText }}
            {% else %}
            <p>{{ news_task.text }}</p>
            {% endif %}
            {% if user.id is defined %}
                {{ render(controller(
                    'App\\Controller\\IndexController::ShowLikeButtons', {'task':news_task.id}
                )) }}
            {% endif %}
        </div>

        <br/>
        <br/>

        {% if comments is defined %}
            <h4>Комментарии</h4>
            {% for comment in comments %}

               <div class="comment_item">
                    <p class="author"><em>Автор: {{ comment.author }}</em></p>
                    <p class="create_date"><em>Дата создания: {{ comment.createDate | date('d.m.Y') }}</em></p>
                    <p class="comment_text">{{ comment.text }}</p>
                </div>
                <hr/>
            {% endfor %}
            <br/>
            <br/>
        {% endif %}

        {% if user.id is defined %}

            <h4>Добавить комментарий</h4>
            {{ form(form) }}
        {% endif %}
        <br/>
        <br/>

        <div>
            <a href="{{ path('news', {'page':1, 'limit':5}) }}">Назад к списку >></a>
        </div>
        <br/>
        <br/>
        <br/>
        <br/>
    </div>
{% endblock %}

templates/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Профиль
{% endblock %}

{% block content %}
    <div class="col">
        <h1>Профиль</h1>

        {% if user.id is defined %}
            <p><b>Имя:</b> {{ user.username }}</p>
            <p><b>Email:</b> {{ user.email }}</p>
            <p><b>Рейтинг:</b> {{ rating }}</p>
        {% endif %}

    </div>
{% endblock %}

templates/tags.html.twig
{% if tags is defined %}
    <h4>Тэги</h4>
    <ul>
        {% for tag in tags %}
            <li>
                <a href="{{ path('news_by_tag', {'tag':tag.id}) }}">{{ tag.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}